services:
  - type: web
    name: n8n
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: "aniket011110"
      - key: N8N_BASIC_AUTH_PASSWORD
        value: "Aniket@9921"
      - key: WEBHOOK_TUNNEL_URL
        value: "https://your-n8n.onrender.com"
